### ISSUE TITLE
Update react-router from 3.x to 4.x

### ISSUE THREAD

**Issue by j1348** [j1348/timelapse-web#15]

**Comment by AlithAnar** [comment]
Can I take it?

**Comment by j1348** [comment]
Sure

**Comment by Shhzdmrz** [comment]
may i work on it? looks like till no one worked on it.

**Comment by jfroffice** [comment]
@AlithAnar any WIP ?

**Comment by j1348** [comment]
@AlithAnar are you still working on it ?

**Comment by Shhzdmrz** [comment]
yeah... just need couple of test.

**Comment by AlithAnar** [comment]
Yep, sorry for no feedback. I had to leave for family reasons. Im on it currently.

**Comment by AlithAnar** [comment]
PR sent.

**Comment by j1348** [comment]
Fix by PR #17 thanks to @AlithAnar
